import { Button, VerticalBox, Slider, HorizontalBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> length: round(slider.value);
    in-out property <string> password: "";
    callback button-pressed <=> button.clicked;
    
    background: #1E2227;
    VerticalBox {
        padding: 20px;
        min-width: 300px;
        preferred-width: 300px;
        Text {
            color: white;
            text: "Password Generator";
            font-size: 20px;
        }
        
        HorizontalBox {
            slider := Slider {
                value: 20;
            }
    
            Text {
                
                text: "Value: \{round(slider.value)}";
                color: white;
            }
        }

        button := Button {
            text: "Generate";
            primary: true;
            clicked => {
                root.length = round(slider.value);
            }
        }

        Text {
            color: white;
            text: "\{root.password}";
        }

    }
}
